services:
    service:
        build: ./
        image: tinyrestcallbackservice:latest
        ports:
            - 5080
        volumes:
            - ${TINYRESTCALLBACKSERVICE_DATA}:/TinyRestCallbackService/data/
        restart: unless-stopped
        #entrypoint: "/usr/bin/python3 -u tinyrestcallbackservice.py data/config.toml"
    webhook-testservice:
        build: ./
        image: tinyrestcallbackservice:latest
        ports:
            - 5081
        restart: unless-stopped
        entrypoint: "/usr/bin/python3 -u ./tools/webhook_testservice.py 5081"