services:
    service:
        build: ./
        image: tinyhttpcallbackservice:latest
        ports:
            - 5080
        volumes:
            - ${TINYHTTPCALLBACKSERVICE_CONFIG}:/TinyHttpCallbackService/config/config.toml
            - ${TINYHTTPCALLBACKSERVICE_DATABASE}:/TinyHttpCallbackService/databases/tinyhttpcallbackservice.db
        restart: unless-stopped
        environment:
            - PYTHONUNBUFFERED=1
    webhook-testservice:
        build: ./
        image: tinyhttpcallbackservice:latest
        ports:
            - 5081
        restart: unless-stopped
        environment:
            - PYTHONUNBUFFERED=1
        entrypoint: "/usr/bin/python3 -u ./tools/webhook_testservice.py"