CREATE TABLE
    ENDPOINT_CONFIG
    (
        ENDPOINT TEXT,
        METHOD TEXT,
        LOG BOOLEAN,
        MESSAGE TEXT,
        REDIRECT_URL TEXT,
        REDIRECT_WAIT INTEGER,
        WEBHOOK_URL TEXT,
        WEBHOOK_METHOD TEXT,
        WEBHOOK_BODY TEXT,
        PRIMARY KEY ( ENDPOINT, METHOD )
    );

CREATE TABLE
    LOG(
        ENDPOINT TEXT,
        METHOD TEXT,
        TIMESTAMP DATETIME,
        HOST TEXT,
        REMOTE_IP TEXT,
        USER_AGENT TEXT
    );